# SPDX-FileCopyrightText: 2022-2023 Eduardo Robles <edu@sequentech.io>
# SPDX-FileCopyrightText: 2022 Félix Robles <felix@sequentech.io>
#
# SPDX-License-Identifier: AGPL-3.0-only

name: 'CI | Benchmark'
on:
  workflow_dispatch: # allows manual triggering
  push:

jobs:
  benchmark:
    name: 'Benchmark'
    uses: sequentech/meta/.github/workflows/benchmark.yml@main
    with:
      cachix-auth-identity: '${{ vars.CACHIX_AUTH_IDENTITY }}'
      cargo-bench-command: >-
        cargo bench
            --bench shuffle
            --bench encrypt
            -- --output-format bencher | tee output.txt
    secrets:
      cachix-auth-token: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      github-token: '${{ secrets.GITHUB_TOKEN }}'
