# SPDX-FileCopyrightText: 2022-2023 Eduardo Robles <edu@sequentech.io>
# SPDX-FileCopyrightText: 2022 Félix Robles <felix@sequentech.io>
#
# SPDX-License-Identifier: AGPL-3.0-only

name: 'CI | Cargo check'
on:
  workflow_dispatch: # allows manual triggering
  push:

jobs:
  cargo-check:
    name: 'Cargo check'
    uses: sequentech/meta/.github/workflows/cargo-check.yml@main
    with:
      cachix-auth-identity: '${{ vars.CACHIX_AUTH_IDENTITY }}'
    secrets:
      cachix-auth-token: '${{ secrets.CACHIX_AUTH_TOKEN }}'
