# SPDX-FileCopyrightText: 2022-2023 Eduardo Robles <edu@sequentech.io>
# SPDX-FileCopyrightText: 2020 GitHub
#
# SPDX-License-Identifier: MIT
# based on https://github.com/actions/starter-workflows/blob/main/pages/static.yml

name: 'CD | Github Pages'
on:
  workflow_dispatch: # allows manual triggering
  push:
    branches: [$default-branch]

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  # To deploy to Pages:
  pages: write
  # To verify the deployment originates from an appropriate source:
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  gh_pages:
    name: Publish on Github Pages
    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3.0.2
    - uses: cachix/install-nix-action@v17
      with:
        install_url: https://github.com/numtide/nix-unstable-installer/releases/download/nix-2.10.0pre20220629_b7eb4ac/install
        nix_path: nixpkgs=channel:nixos-22.05
        extra_nix_config: |
          experimental-features = nix-command flakes

    - uses: cachix/cachix-action@v10
      with:
        name: sequentech
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'

    - name: Build the WASM Test code
      run: |
        nix \
          --extra-experimental-features "nix-command flakes" \
          develop \
          --command bash -c "RUSTFLAGS='-C target-feature=+atomics,+bulk-memory,+mutable-globals' wasm-pack build --out-name index --release --target web --features=wasmtest,wasmrayon -- -Z build-std=panic_abort,std"
 
    - name: Add pkg to deploy and list files in deployment dir
      run: |
        cp -r ./pkg/ ./src/wasm/test/pkg/
        ls -lah ./src/wasm/test/

    - name: Setup GH Pages
      uses: actions/configure-pages@v2

    - name: Upload pages artifact
      uses: actions/upload-pages-artifact@v1
      with:
        path: ./src/wasm/test/
        retention-days: 365

    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v1
