# SPDX-FileCopyrightText: 2022-2023 Eduardo Robles <edu@sequentech.io>
# SPDX-FileCopyrightText: 2022 Félix Robles <felix@sequentech.io>
#
# SPDX-License-Identifier: AGPL-3.0-only

name: 'CI | Lint'
on:
  workflow_dispatch: # allows manual triggering
  push:

jobs:
  lint:
    name: 'Lint'
    uses: sequentech/meta/.github/workflows/lint.yml@main
    with:
      cachix-auth-identity: '${{ vars.CACHIX_AUTH_IDENTITY }}'
      rust: true
    secrets:
      cachix-auth-token: '${{ secrets.CACHIX_AUTH_TOKEN }}'
