
# SPDX-FileCopyrightText: 2022-2023 Eduardo Robles <edu@sequentech.io>
#
# SPDX-License-Identifier: AGPL-3.0-only
name: 'CI | ORT'

on:
  workflow_dispatch: # allows manual triggering
  push:

jobs:
  ort:
    name: 'ORT'
    uses: sequentech/meta/.github/workflows/ort.yml@main
    with:
      ort-cli-analyze-args: '--package-managers Cargo'
