# SPDX-FileCopyrightText: 2022 Eduardo Robles <edu@sequentech.io>
# SPDX-FileCopyrightText: 2022 Félix Robles <felix@sequentech.io>
#
# SPDX-License-Identifier: AGPL-3.0-only

name: update-flake-lock
on:
  workflow_dispatch: # allows manual triggering
  schedule:
    # minute, hour, day of month, month, day of week
    - cron: '0 0 * * 1' # runs weekly on Monday at 00:00

jobs:
  lockfile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3.0.2

      - name: Install Nix
        uses: cachix/install-nix-action@v17
      
      - uses: cachix/cachix-action@v10
        with:
          name: sequenttech
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      
      - name: Update flake.lock
        uses: DeterminateSystems/update-flake-lock@v10
        with:
          token: ${{ secrets.GH_TOKEN_FOR_UPDATES }}
          pr-title: "Update flake.lock" # Title of PR to be created
          pr-labels: |                  # Labels to be set on the PR
            dependencies
